#!/usr/bin/env python3
"""Create an ignored Run N9.command with explicit source-build selections."""
import argparse
import os
from pathlib import Path
import shlex
import shutil
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]


def executable(value):
    found = shutil.which(value)
    if not found:
        raise ValueError('Executable not found: ' + value)
    return str(Path(found).resolve())


def validate_build(root, network, skin):
    for relative in ('qemu-system-arm', 'qemu-img',
                     'meson-info/intro-buildoptions.json',
                     'Harmattan N9.app/Contents/MacOS/qemu-system-arm'):
        if not (root / relative).is_file():
            raise ValueError('Missing native build file: ' + relative)
    if network == 'user':
        for relative in ('qemu-system-arm', 'Harmattan N9.app/Contents/MacOS/qemu-system-arm'):
            if b'n00-smc91c111-window' not in (root / relative).read_bytes():
                raise ValueError('Selected QEMU build lacks the N00 networking patch: ' + relative)
    if skin == 'black' and not (root / 'Harmattan N9.app/Contents/Resources/n9-black-livven.png').is_file():
        raise ValueError('Selected build does not contain the user-supplied black frame')


def render(repo, settings, audio):
    lines = ['#!/bin/sh', '# Local selections generated by scripts/create-local-launcher.py; keep private.',
             'set -eu', 'umask 077', 'cd ' + shlex.quote(str(repo))]
    for name, value in settings.items():
        # Assign the literal separately: quotes inside ${VAR:-literal} do not
        # safely preserve arbitrary shell metacharacters in a private path.
        lines += ['selection=' + shlex.quote(str(value)),
                  'export ' + name + '="${' + name + ':-$selection}"']
    lines += ['case "${1:-interactive}" in',
              '  interactive|--usability-diagnostic|--usability-headless-diagnostic|--audio-diagnostic)',
              '    default_audio=' + shlex.quote(audio) + ' ;;',
              '  *) default_audio=off ;;',
              'esac', 'export HARMATTAN_UI_AUDIO="${HARMATTAN_UI_AUDIO:-$default_audio}"',
              'mkdir -p "$HARMATTAN_PORT_WORKSPACE"',
              'printf "Network: %s; audio: %s\\n" "$HARMATTAN_UI_NETWORK" "$HARMATTAN_UI_AUDIO"',
              'exec /bin/sh scripts/harmattan-qemu/run-arm64-ui.sh "$@"']
    return '\n'.join(lines) + '\n'


def write_launcher(output, content, replace=False):
    if output.is_symlink() or (output.exists() and not output.is_file()):
        raise ValueError('Launcher destination must be a regular file')
    if output.exists() and not replace:
        raise ValueError('Launcher exists; --replace retains a private backup before updating it')
    output.parent.mkdir(parents=True, exist_ok=True)
    backup = None
    if output.exists():
        fd, name = tempfile.mkstemp(prefix=output.name + '.previous-', dir=output.parent)
        with os.fdopen(fd, 'wb') as stream:
            stream.write(output.read_bytes())
        backup = Path(name)
    fd, name = tempfile.mkstemp(prefix='.launcher-', dir=output.parent)
    try:
        with os.fdopen(fd, 'w') as stream:
            stream.write(content)
        os.chmod(name, 0o755)
        os.replace(name, output)
    finally:
        if os.path.exists(name):
            os.unlink(name)
    return backup


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--build-root', type=Path, required=True, help='verified Cocoa interaction build directory')
    parser.add_argument('--workspace', type=Path, default=ROOT / 'extracted/local-n9-runs')
    parser.add_argument('--armel-clang', default='clang')
    parser.add_argument('--debugfs', default='debugfs')
    parser.add_argument('--network', choices=('off', 'user'), default='off')
    parser.add_argument('--audio', choices=('off', 'pulse'), default='off')
    parser.add_argument('--pulseaudio', default='pulseaudio')
    parser.add_argument('--skin', choices=('off', 'frame', 'black'), default='off')
    parser.add_argument('--replace', action='store_true')
    args = parser.parse_args()
    try:
        if sys.version_info < (3, 12):
            raise ValueError('Use Python 3.12 or newer')
        build = args.build_root.expanduser().resolve(strict=True)
        network = 'user' if args.audio == 'pulse' else args.network
        validate_build(build, network, args.skin)
        settings = {'HARMATTAN_UI_BUILD_ROOT': build,
                    'HARMATTAN_PORT_WORKSPACE': args.workspace.expanduser().resolve(),
                    'HARMATTAN_PYTHON': Path(sys.executable).resolve(),
                    'HARMATTAN_ARMEL_CLANG': executable(args.armel_clang),
                    'HARMATTAN_DEBUGFS': executable(args.debugfs),
                    'HARMATTAN_UI_SKIN': args.skin, 'HARMATTAN_UI_NETWORK': network}
        if args.audio == 'pulse':
            pulse = Path(executable(args.pulseaudio))
            for name in ('pactl', 'parec'):
                if not os.access(pulse.with_name(name), os.X_OK):
                    raise ValueError('PulseAudio requires matching ' + name)
            settings['HARMATTAN_PULSEAUDIO'] = pulse
        output = ROOT / 'artifacts/local/Run N9.command'
        backup = write_launcher(output, render(ROOT, settings, args.audio), args.replace)
        print(output)
        print('Network:', network, '; audio:', args.audio)
        if backup:
            print('Previous launcher retained:', backup)
        print('Selections are validated when launched; existing QEMU sessions keep their original settings.')
    except (OSError, ValueError) as error:
        parser.exit(1, str(error) + '\n')


if __name__ == '__main__':
    main()
